### PR TITLE
Fix array union bug + a new example to get followers

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Comment by julien-c** [comment]
The same array union bug might be present in other example files, too (I just checked this one)

**Comment by themattharris** [comment]
Crazy silly error on my part, thanks for catching this.
The fix will be in tmhOAuth 0.62.
I'm going to skip the followers example in favour of adding a comment at the top of friends.php - i don't think it's necessary to add an explicit example for followers when the only difference is the URL.

**Comment by julien-c** [comment]
Sure. Re-reading my comment, I think I meant "I just checked IN this one" -- I think I remember seeing other occurences of += array merging in other examples (PHP syntax's not too straightforward on this one though). Thanks!

**Comment by themattharris** [comment]
Just pushed 0.62 with this in it live.

**Pull request closed without merging**
