### PR TITLE
Allows curl to work in AWS enviroment

### PR DESCRIPTION
**Pull request by troykelly**
AWS environment has somewhat broken curl - need to set SSLVERSION to 3 for it to work from PHP

### CODE REVIEW

**Comment by themattharris** [comment]
hey, thanks for the pull request.
can you give me a little more info on what this change is doing and what happens on AWS when it's not set?

the reason i ask is setting this value to 3 is inherently less secure than leaving it as CURLOPT_SSLVERSION_DEFAULT -- which would instead negotiate the highest TLS version if can before downgrading to SSLv3.

**Comment by troykelly** [comment]
There's a "fix" (horrible hack) to get curl working again on elastic beanstalk, so it's not super critical.

The default build of curl on elastic beanstalk doesn't work with SSL properly. The "fix" of setting to 3 is a hack to get around EB's problems.

A better way to do it would be to try and catch the failing curl call, and fall back to 3 - but giving it causes php to completely fail - I don't even know if this will work.

I guess short term it might just be better to allow the user to pass the version in the config?

Regards,
Troy Kelly
Aperim Pty Ltd
+61 2 8905 0770
http://aperim.com/

Sent from a mobile device, please forgive any err0rs

> On 14 May 2014, at 4:32 pm, Matt Harris notifications@github.com wrote:
> 
> hey, thanks for the pull request.
> can you give me a little more info on what this change is doing and what happens on AWS when it's not set?
> 
> the reason i ask is setting this value to 3 is inherently less secure than leaving it as CURLOPT_SSLVERSION_DEFAULT -- which would instead negotiate the highest TLS version if can before downgrading to SSLv3.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Aperim Pty Ltd ACN 150 699 737
Disclaimer - Unless clearly stated otherwise this email and any files 
transmitted with it should be considered without prejudice and are 
confidential and contain privileged or copyright information.
You must not present this message to another party without gaining 
permission from the sender. If you are not the intended recipient you must 
not copy, distribute or use this email or the information contained in it 
for any purpose other than to notify us.
Any views expressed in this message are those of the individual sender, 
except where the sender specifically states them to be the views of this 
company or its subsidiaries.

**Comment by themattharris** [comment]
yeah. i'd prefer not defaulting people to a lower security setting. but oddities occur so i agree an option for this would be helpful.

adding an approach to this into 0.8.4

**Comment by themattharris** [comment]
catching up, lots going on. 0.8.4 just merged to master and i've added a config entry for CURLOPT_SSLVERSION.

**Pull request closed without merging**
