### PR TITLE
Fixed composer.json

### PR DESCRIPTION
**Pull request by rasa**
I tried using https://github.com/themattharris/tmhOAuth.git with `composer`, by adding

```
{
    "type": "vcs",
    "url": "git://github.com/themattharris/tmhOAuth.git"
},
"require": {
    "themattharris/tmhOAuth": "master" (or "dev-master")
}
```

to my app's `composer.json` and ran `composer install`, but it always pulled the 0.7.2-devel branch, and not the master.

I then tried

```
"require": {
    "themattharris/tmhOAuth": "0.7.2"
}
```

but for some reason `composer` fails to even process the entry then.

I then tried

```
"require": {
    "themattharris/tmhOAuth": "*"
}
```

and still got the 0.7.2 branch.

I then reviewed https://github.com/themattharris/tmhOAuth/blob/master/composer.json and see that the package requires itself! (https://github.com/themattharris/tmhOAuth/blob/master/composer.json#L28). It also hardcodes the version, and the classmap is wrong.

I tested the updated `composer.json`, and it works fine. Please use it.

### CODE REVIEW

**Comment by markushausammann** [comment]
:+1:

**Comment by markushausammann** [comment]
For a new composer installable version, just create a git tag, packagist will take care of the rest.

**Comment by themattharris** [comment]
thanks for bumping and correct this file. i should be able to add this into the library on monday and push out 0.7.3 on that day.

**Comment by ceeram** [comment]
https://packagist.org/packages/themattharris/tmhoauth does not point to your repo, but to kud/tmhoauth

**Comment by themattharris** [comment]
yup i know. i didn't create the package and was surprised to find other people claiming authorship of it.

**Comment by themattharris** [comment]
merge into 0.7.3 and shipped

**Pull request closed without merging**
