### PR TITLE
Adding Composer Support

### PR DESCRIPTION
**Pull request by akandels**
Adds a composer.json file which would allow composer to install your tool in projects and setup autoloading.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Yes please.

#39 suggests adding namespaces for the sake of it, and hosts a good discussion but can easily be closed.
#77 shows how it should be done for 0.7.1 (at which point you said you'd look into full PSR-0 compliance)

But this pull request will triage it well enough for us to be able to use the package in Composer and have it listed on Packagist. Classmap will allow full integration without the requirement of moving to PSR-0 (which is definitely a good move).

6 months ago PHP 5.2 was still so widespread it mattered. Now I am migrating applications like PyroCMS to PHP 5.3 because even companies like MediaTemple no longer offer PHP 5.2! 5.2 is basically dead and gone at the point, so its a perfect time to uptake PSR-0.

**Comment by julien-c** [comment]
+1

**Comment by themattharris** [comment]
ok i've committed a variant of your pull request to the 0.7.2-devel branch. let me know if it's good to go.
i'm also going to close and link issue #39 and #77 to here so we have one place to track things

**Comment by philsturgeon** [comment]
Good man, thank you!

**Pull request closed without merging**
